on: push
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@latest
    - uses: DeLaGuardo/setup-graalvm@2.0
      with:
        graalvm-version: '19.3.1.java11'
    - uses: DeLaGuardo/setup-clojure@master
      with:
        cli: '1.10.1.469'
    - run: clojure -Sdescribe
