on: push
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1.4.3
      with:
        java-version: '11'
    - uses: DeLaGuardo/setup-clojure@master
      with:
        cli: '1.10.1.469'
    - run: clojure -A:fig:min
