on: push
jobs:
  build_and_publish:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1.4.3
      with:
        java-version: '11'
    - uses: DeLaGuardo/setup-clojure@master
      with:
        cli: '1.10.1.469'
    - run: clojure -A:fig:min
    - run: mkdir build-out-{$GITHUB_SHA}
    - run: cp target/out/cljs-out build-out-{$GITHUB_SHA}/cljs-out
    - run: cp resources/public/* build-out-{$GITHUB_SHA}/
    - run: ls build-out-{$GITHUB_SHA}
